# Generated by Django 3.2.3 on 2022-06-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_alter_user_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_on_board_remainder_send',
            field=models.BooleanField(default=False),
        ),
    ]
