# Generated by Django 3.2.3 on 2022-07-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_user_is_on_board_remainder_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_on_board_remainder_send',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
