# Generated by Django 3.2.3 on 2022-06-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0009_alter_leadsmodel_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsmodel',
            name='company_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'E_COMMERCE'), (2, 'MOBILE_APP'), (3, 'SAAS'), (4, 'SUBSCRIPTION'), (5, 'OTHER')], null=True),
        ),
    ]
